{{- if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    {{- include "kafka-lab.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  selector:
    {{- include "kafka-lab.selectorLabels" (dict "context" . "component" "api") | nindent 4 }}
  ports:
    - port: {{ .Values.api.port }}
      targetPort: {{ .Values.api.port }}
  type: {{ .Values.api.service.type }}
{{- end }}
