apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kafka-lab.configmapName" . }}
  labels:
    {{- include "kafka-lab.labels" . | nindent 4 }}
data:
  KAFKA_BROKER: {{ .Values.kafka.brokers | quote }}
  KAFKA_USE_MSK: {{ .Values.kafka.useMsk | quote }}
  AWS_REGION: {{ .Values.region | quote }}
