apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kafka-lab.configmapName" . }}
  labels:
    {{- include "kafka-lab.labels" . | nindent 4 }}
data:
  KAFKA_USE_MSK: {{ .Values.kafka.useMsk | quote }}
  AWS_REGION: {{ .Values.region | quote }}
  {{- if .Values.otel.enabled }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.otel.collectorEndpoint | quote }}
  OTEL_EXPORTER_OTLP_INSECURE: {{ .Values.otel.insecure | quote }}
  OTEL_DEPLOYMENT_ENVIRONMENT: {{ .Values.otel.environment | quote }}
  {{- end }}
