{{- if .Values.externalSecrets.enabled }}
{{- if and .Values.producer.enabled .Values.producer.secretPath }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "kafka-lab.fullname" . }}-producer
  labels:
    {{- include "kafka-lab.labels" . | nindent 4 }}
    app.kubernetes.io/component: producer
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: producer-secret-store
    kind: SecretStore
  target:
    name: {{ include "kafka-lab.producerSecretName" . }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.producer.secretPath }}
{{- end }}
---
{{- if and .Values.consumer.enabled .Values.consumer.secretPath }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "kafka-lab.fullname" . }}-consumer
  labels:
    {{- include "kafka-lab.labels" . | nindent 4 }}
    app.kubernetes.io/component: consumer
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: consumer-secret-store
    kind: SecretStore
  target:
    name: {{ include "kafka-lab.consumerSecretName" . }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.consumer.secretPath }}
{{- end }}
---
{{- if and .Values.api.enabled .Values.api.secretPath }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "kafka-lab.fullname" . }}-api-secrets
  labels:
    {{- include "kafka-lab.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: api-secret-store
    kind: SecretStore
  target:
    name: {{ include "kafka-lab.apiSecretsName" . }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.api.secretPath }}
{{- end }}
{{- end }}
