apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    {{- include "kafka-lab.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  selector:
    {{- include "kafka-lab.selectorLabels" (dict "context" . "component" "frontend") | nindent 4 }}
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
  type: {{ .Values.frontend.service.type }}
