{{- if and .Values.ingress.enabled .Values.ingress.regionalHostname }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "kafka-lab.fullname" . }}-ingress-regional
  labels:
    {{- include "kafka-lab.labels" . | nindent 4 }}
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/healthcheck-path: /api/health
    alb.ingress.kubernetes.io/healthcheck-port: "8000"
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.ingress.regionalHostname }}
spec:
  ingressClassName: alb
  rules:
    - host: {{ .Values.ingress.regionalHostname }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: {{ .Values.api.port }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: {{ .Values.frontend.port }}
{{- end }}