{{- if .Values.producer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kafka-lab.fullname" . }}-producer
  labels:
    {{- include "kafka-lab.labels" . | nindent 4 }}
    app.kubernetes.io/component: producer
spec:
  replicas: {{ .Values.producer.replicas }}
  selector:
    matchLabels:
      {{- include "kafka-lab.selectorLabels" (dict "context" . "component" "producer") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kafka-lab.selectorLabels" (dict "context" . "component" "producer") | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.producer.serviceAccount.name | default "producer" }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: producer
          image: {{ .Values.producer.image.repository }}:{{ .Values.producer.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          command: ["python", "producer.py"]
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          env:
            - name: KAFKA_BROKER
              valueFrom:
                secretKeyRef:
                  name: {{ include "kafka-lab.producerSecretName" . }}
                  key: KAFKA_BROKER
            - name: KAFKA_USE_MSK
              valueFrom:
                configMapKeyRef:
                  name: {{ include "kafka-lab.configmapName" . }}
                  key: KAFKA_USE_MSK
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: {{ include "kafka-lab.configmapName" . }}
                  key: AWS_REGION
            - name: MSG_PER_SEC
              value: {{ .Values.producer.msgPerSec | quote }}
            - name: USE_MESSAGE_KEY
              value: {{ .Values.producer.useMessageKey | quote }}
          resources:
            {{- toYaml .Values.producer.resources | nindent 12 }}
      volumes:
        - name: tmp
          emptyDir: {}
{{- end }}
