apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kafka-lab.apiSecretName" . }}
  labels:
    {{- include "kafka-lab.labels" . | nindent 4 }}
type: Opaque
stringData:
  MEMCACHED_HOST: {{ .Values.cache.host | quote }}
  MEMCACHED_PORT: {{ .Values.cache.port | quote }}
