apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kafka-lab.oracleSecretName" . }}
  labels:
    {{- include "kafka-lab.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USER: {{ .Values.database.user | quote }}
  DB_PASSWORD: {{ .Values.database.password | quote }}
  DB_DSN: {{ .Values.database.dsn | quote }}
