{{- if not .Values.externalSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kafka-lab.consumerSecretName" . }}
  labels:
    {{- include "kafka-lab.labels" . | nindent 4 }}
type: Opaque
stringData:
  KAFKA_BROKER: {{ .Values.kafka.brokers | quote }}
  DB_USER: {{ .Values.database.user | quote }}
  DB_PASSWORD: {{ .Values.database.password | quote }}
  DB_DSN: {{ .Values.database.dsn | quote }}
  DB_WRITER_DSN: {{ include "kafka-lab.writerDsn" . | quote }}
{{- end }}
