{{- if not .Values.externalSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kafka-lab.apiSecretsName" . }}
  labels:
    {{- include "kafka-lab.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USER: {{ .Values.database.user | quote }}
  DB_PASSWORD: {{ .Values.database.password | quote }}
  DB_DSN: {{ .Values.database.dsn | quote }}
  DB_READER_DSN: {{ include "kafka-lab.readerDsn" . | quote }}
  CACHE_HOST: {{ .Values.cache.host | quote }}
  CACHE_PORT: {{ .Values.cache.port | quote }}
  CACHE_TLS: {{ .Values.cache.tls | quote }}
  CACHE_COUNT_TTL: {{ .Values.cache.countTtl | quote }}
  {{- if .Values.cache.password }}
  CACHE_PASSWORD: {{ .Values.cache.password | quote }}
  {{- end }}
{{- end }}
