apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kafka-lab.apiSecretName" . }}
  labels:
    {{- include "kafka-lab.labels" . | nindent 4 }}
type: Opaque
stringData:
  CACHE_HOST: {{ .Values.cache.host | quote }}
  CACHE_PORT: {{ .Values.cache.port | quote }}
  CACHE_TLS: {{ .Values.cache.tls | quote }}
